### ISSUE TITLE
Impossible to send request without or invalid Content-Type header.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#496]
_From [kaliba...@gmail.com](https://code.google.com/u/113461663865567464229/) on June 26, 2014 14:41:49_

1. Send the request and don't add any headers.

I expected that rest assured will send request without any headers. Instead of this assured is adding default header of Content-Type which I don't want it.

2. Add header for e.g. Content-Type/testingName and send request.

I expected that assured will send request but it is trying to encode it and I got "Don't know how to encode" error.

I didn't found any solution for this issues. Not on this page and not while searching by google :(

I'm using version 2.3.0 on Win8.

I know that Content-Type should be set, but I want to test some service, and my test case require missing Content-Type or invalid. So I would be great to have that possibility. At least activating some additional flag.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=341_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 05, 2014 10:07:28_

It's not supported right now but I see no reason for not supporting it. If you like please try to help out with a pull request.

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 05, 2014 10:08:25_

**Status:** Duplicate  
  **Mergedinto:** 226

**Comment by GayaneD** [comment]
Hi @johanhaleby.
I see the issue is closed long time back but it is still actual for us. We are using **Rest Assured 4.3.3** with JAVA, Cucumber JVM.
When we try to send invalid **ContentType = application/json1**  for our negative test  we receive the following error:
`      java.lang.IllegalArgumentException: **Don't know how to encode** {  "version": "1.0",  "recordtype": "inventoryitem",  "externalid": "4000007626100357914",  "liveonwebdate": "1900-01-01T00:00:00.000",  "visualmerchreadyflag": "true"} a
s a byte stream.
Please use EncoderConfig (EncoderConfig#encodeContentTypeAs) to specify how to serialize data for this content-type.
For example: "given().config(RestAssured.config().encoderConfig(encoderConfig().encodeContentTypeAs("application/json1", ContentType.TEXT))). .."`

Could you please advice on this? Is the issue still open? And if yes, what workaround would you advice?
