### ISSUE TITLE
XmlPath behavior differs when namespaces are present

### ISSUE THREAD

**Issue by dave-r12** [jayway/rest-assured#576]
While using XmlPath, I noticed the behavior differs depending on whether I use namespaces. I'm unsure if this is user error, is expected or unexpected but thought I'd report it. Consider this example:

```java
  public static void main(String[] args) {
    String someXml = "" +
        "<outer>" +
        "  <middle>" +
        "    <inner>1</inner>" +
        "  </middle>" +
        "</outer>";

    XmlPath xmlPath = XmlPath.from(someXml);
    System.out.println(xmlPath.get("outer.middle.inner")); // Prints 1
    System.out.println(xmlPath.get("middle.inner")); // print empty

    String moreXml = "" +
        "<n:outer xmlns:n=\"http://localhost\">" +
        "  <n:middle>" +
        "    <n:inner>2</n:inner>" +
        "  </n:middle>" +
        "</n:outer>";

    xmlPath = XmlPath.from(moreXml).using(xmlPathConfig().declaredNamespace("n", "http://localhost"));
    System.out.println(xmlPath.get("n:outer.n:middle.n:inner")); // prints empty
    System.out.println(xmlPath.get("n:middle.n:inner")); // print 2
  }
```

**Comment by johanhaleby** [comment]
Yes I agree that it's strange but I think it works according to how [XmlSlurper](http://docs.groovy-lang.org/latest/html/api/groovy/util/XmlSlurper.html) works in Groovy (which REST Assured is based on). It seems like the root element is just ignored when declaring a namespace. Don't ask me why (but you could ask on the Groovy mailinglist and then tell me :)). See for example here: http://stackoverflow.com/a/8670254/398441. I'm going to close the issue since REST Assured tries to be as close to Groovy as possible. If you find out that I'm wrong and Groovy works differently I'm happy to reopen the issue and fix it.

**Comment by dave-r12** [comment]
Gotcha, thanks
