### ISSUE TITLE
Function "JsonPath.getList()" returns null when key contains a hyphen "-"

### ISSUE THREAD

**Issue by joshdk** [jayway/rest-assured#601]
(Migrated from jayway/JsonPath/issues/140)

Hello,

I am pulling in `com.jayway.restassured:json-path:2.6.0` as a dependency of `com.jayway.restassured:rest-assured:2.6.0` (which is fantastic by the way!). When attempting to validate some properties of a JSON API, I ran into the following case, which looks like a bug.

Given a JSON document like `{"key-name":["value1", "value2"]}`, I can call `JsonPath.getString("\"key-name\"[0]")` to get the first list value `value1`.

**But**, if instead I ask for the entire list with `JsonPath.getList("\"key-name\"")`, I just get `null` instead.

I have validated my syntax using other JSONPath parsers (like https://jsonpath.curiousconcept.com/) and everything looks correct. I have also included sample code below that shows how my syntax **works for key with underscores**, but **fails for keys with hyphens**.

```java
import com.google.common.collect.ImmutableList;
import com.jayway.restassured.path.json.JsonPath;
import org.junit.Assert;
import org.junit.Test;

public final class JsonTest {

    @Test
    public void testParse() {
        String body;
        JsonPath json;

        // Original JSON, notice that the key contains an underscore
        body = "{\"key_name\":[\"value1\", \"value2\"]}";
        json = new JsonPath(body);

        // Assert #1 passes
        Assert.assertEquals(
            "value1",
            json.getString("key_name[0]")
        );

        // Assert #2 passes
        Assert.assertEquals(
            "value1",
            json.getString("\"key_name\"[0]")
        );

        // Assert #3 passes
        Assert.assertEquals(
            ImmutableList.of("value1", "value2"),
            json.getList("\"key_name\"")
        );

        // Same as original JSON, notice that the key contains a hyphen instead of an underscore
        body = "{\"key-name\":[\"value1\", \"value2\"]}";
        json = new JsonPath(body);

        // Assert #4 passes
        Assert.assertEquals(
            "value1",
            json.getString("\"key-name\"[0]")
        );

        // Assert #5 fails
        //java.lang.AssertionError: expected:<[value1, value2]> but was:<null>
        Assert.assertEquals(
            ImmutableList.of("value1", "value2"),
            json.getList("\"key-name\"")
        );
    }

}
```

If there is a workaround that allows me to extract the desired values, that would also be great, as it's completely possible that I'm not escaping something properly.

Thank you!

**Comment by johanhaleby** [comment]
Hi,

JsonPath in REST Assured should not be confused with Jayway's other <a href="https://github.com/jayway/JsonPath">JsonPath</a> project. They are not the same (see [docs](https://github.com/jayway/rest-assured/wiki/Usage#example-1---json)). You can escape properties in REST Assured's JsonPath using single quotes (but must properties are automatically escaped).  So in your case I think you should do:

```java
JsonPath.getString("'key-name'[0]")
```

I've tried to automatically escape hyphens like these for arrays but I've not implemented it yet since it turned out to be difficult if we want to retain backward compatibility (which is not a given btw). Please share your thoughts in this [issue](https://github.com/jayway/rest-assured/issues/564).
