### ISSUE TITLE
why DELETE method won't allow multi-part form data as the body

### ISSUE THREAD

**Issue by zhong88** [jayway/rest-assured#634]
Hi,
Just ran into this issue. When we include a multi-part form param as the body of the DELETE request, it sent out an exception indicating that "multi part form data is only available for POST, PUT and PATCH."
I also looked through the test written in this repo and it seems this is expected behavior https://github.com/jayway/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/com/jayway/restassured/itest/java/MultiPartUploadITest.java. 
In HTTP spec, there's no such constraints on the body of the DELETE method, so here why we do so? could we relax this check?

**Comment by johanhaleby** [comment]
Thanks. I don't remember exactly why I didn't allow it since it was such a long time ago. It might have been some technical issue. Even now when I remove the restriction and modifies the test to actually send something [Scalatra](http://www.scalatra.org/) doesn't seem to handle it properly. It might very well be a "problem" with Scalatra though. When I check what's sent on the wire (in wireshark) the request looks ok to me: 

![image](https://cloud.githubusercontent.com/assets/187029/12504495/3b3c792e-c0de-11e5-81f1-3b6f0e4a95c5.png)

So I need your help. I've deployed a new snapshot of REST Assured with multipart enabled for DELETE. Please try it out and give me feedback on whether or not it works. If it does I'll include it in the next release. So please try version `2.8.1-SNAPSHOT` after having added the following Maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by zhong88** [comment]
Great! I would try out this weekend and let you know the result!
